# -----------------------------
# 1. Data Input
# -----------------------------
input_data_path : '/mnt/c/Tensor/Database/PRICE_RETURNS'
db_name : 'Tensor_Portfolio_simple_return.parquet'
output_data_path : '/mnt/c/Tensor/Database/DENOISED_RETURNS'

# -----------------------------
# 2. Wavelet Denoising
# -----------------------------
denoising_method  : 'wavelet'

# Threshold for Wavelet Denoising (from 0.0 to 1.0)
thresh : 0.1 

# Wavelet Transformation Function
# 'sym2', 'sym3', 'sym4', 'sym5', 'sym6', 
# 'sym7', 'sym8', 'sym9', 'sym10', 'sym11',
# 'sym12', 'sym13', 'sym14', 'sym15', 'sym16', 
# 'sym17', 'sym18', 'sym19', 'sym20'
wavelet : "sym4"

# Candle Stick Upsample Range (in minutes)
minute_sampling : 15

# lookback subset to PACF pattern search
pacf_days_subset : 60

# Number of hours to consider for 
# lag pattern lookup
nn_hours_pattern_lookup : 24

# Local timezone
time_zone : 'Europe/Berlin'

# -----------------------------
# 3. Partial Autocorrelation
# -----------------------------
alpha_pacf : .05
method_pacf : "ols"

