Feature_Engineering:
    1:
      ta: 
        - 
          "kind": "sma"
          "length": 15
        - 
          "kind": "sma" 
          "length": 120
        - 
          "kind": "vwma" 
          "length": 60
        - 
          "kind": "vwma" 
          "length": 15
        -
          "kind": "bbands"
          "length": 15
        - 
          "kind": "bbands"
          "length": 120
        - 
          "kind": "macd"
          "fast": 15
          "slow": 120
        - 
          "kind": "rsi" 
          "length": 15 
        - 
          "kind": "atr"
          "length": 15
        - 
          'kind': "pdist"
      
      'include_lags': True
      'lags': [1,3,5,15,30]
      'ref_variable_lags' : ["Close"]
      'drop_lags': False

      'Volume_Features': True
      'Volume_Col': 'Volume'
      'Volume_Windows': [5, 30]

      'EntryPrice_PrevClose': False
      'lags_diff' : [1,15,30,60]
      'binary_lags': False

      'Return_Features': True
      'return_lags': [1, 5, 15, 60, 240]
      'return_lags_variable' : 'Close'
      'Momentum_Features': True

      'Time_Features': True
      'Time_Fourier_Features': False

      'use_prob_features': True
      'probability_features' : ['entry_type', 'risk_type']
      'Prob_Features_Windows': [2,6]

      'Apply_Standard_Scaler': True
      'Standard_Scaler_Cols': ['Volume', 'Number of Trades']