SYMBOLS = [ 'BTCUSDT', 'ETHUSDT', 'LTCUSDT',  'ADAUSDT','BNBUSDT', 'BNBBTC' , 'EOSUSDT', 'ETCUSDT',
        'XMRBTC', 'TRXUSDT', 'XLMUSDT', 'IOTAUSDT',
        'MKRUSDT', 'DOGEUSDT']


INTERVAL = "1m"